/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

/**
 *
 * @author Win 10
 */
public class frmhomepage extends javax.swing.JFrame {

    /**
     * Creates new form frmhomepage
     */
    public frmhomepage() {
        initComponents();
        pnlmenu.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        btnnewpro = new javax.swing.JButton();
        viewpro = new javax.swing.JButton();
        trackpro = new javax.swing.JButton();
        pnlmenu = new javax.swing.JPanel();
        btnhomem = new javax.swing.JButton();
        btnnewprom = new javax.swing.JButton();
        btnviewprom = new javax.swing.JButton();
        btntrackingm = new javax.swing.JButton();
        btnlogout = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnmenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("WMS home");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Warehouse Mangement System");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 21, -1, 37));

        btnnewpro.setBackground(new java.awt.Color(31, 42, 56));
        btnnewpro.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnnewpro.setForeground(new java.awt.Color(255, 255, 255));
        btnnewpro.setText("add new products");
        btnnewpro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnnewpro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnewproActionPerformed(evt);
            }
        });
        getContentPane().add(btnnewpro, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 107, 297, 69));

        viewpro.setBackground(new java.awt.Color(31, 42, 56));
        viewpro.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        viewpro.setForeground(new java.awt.Color(255, 255, 255));
        viewpro.setText("view products");
        viewpro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(viewpro, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 226, 297, 69));

        trackpro.setBackground(new java.awt.Color(31, 42, 56));
        trackpro.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        trackpro.setForeground(new java.awt.Color(255, 255, 255));
        trackpro.setText("products tracking");
        trackpro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(trackpro, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 336, 297, 69));

        pnlmenu.setBackground(new java.awt.Color(31, 42, 56));
        pnlmenu.setBorder(new javax.swing.border.MatteBorder(null));
        pnlmenu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnhomem.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnhomem.setForeground(new java.awt.Color(255, 255, 255));
        btnhomem.setText("home");
        btnhomem.setBorderPainted(false);
        btnhomem.setContentAreaFilled(false);
        btnhomem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnhomem.setFocusPainted(false);
        btnhomem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhomemActionPerformed(evt);
            }
        });

        btnnewprom.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnnewprom.setForeground(new java.awt.Color(255, 255, 255));
        btnnewprom.setText("new products");
        btnnewprom.setBorderPainted(false);
        btnnewprom.setContentAreaFilled(false);
        btnnewprom.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnnewprom.setFocusPainted(false);

        btnviewprom.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnviewprom.setForeground(new java.awt.Color(255, 255, 255));
        btnviewprom.setText("view products");
        btnviewprom.setBorderPainted(false);
        btnviewprom.setContentAreaFilled(false);
        btnviewprom.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnviewprom.setFocusPainted(false);

        btntrackingm.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btntrackingm.setForeground(new java.awt.Color(255, 255, 255));
        btntrackingm.setText("tracking");
        btntrackingm.setBorderPainted(false);
        btntrackingm.setContentAreaFilled(false);
        btntrackingm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btntrackingm.setFocusPainted(false);
        btntrackingm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntrackingmActionPerformed(evt);
            }
        });

        btnlogout.setForeground(new java.awt.Color(255, 255, 255));
        btnlogout.setText("logout\n");
        btnlogout.setBorderPainted(false);
        btnlogout.setContentAreaFilled(false);
        btnlogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnlogout.setFocusPainted(false);

        javax.swing.GroupLayout pnlmenuLayout = new javax.swing.GroupLayout(pnlmenu);
        pnlmenu.setLayout(pnlmenuLayout);
        pnlmenuLayout.setHorizontalGroup(
            pnlmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlmenuLayout.createSequentialGroup()
                .addGroup(pnlmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnnewprom)
                    .addComponent(btnviewprom))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnlmenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnlogout)
                    .addComponent(btntrackingm)
                    .addComponent(btnhomem))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlmenuLayout.setVerticalGroup(
            pnlmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlmenuLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(btnhomem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnnewprom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnviewprom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btntrackingm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 254, Short.MAX_VALUE)
                .addComponent(btnlogout)
                .addContainerGap())
        );

        getContentPane().add(pnlmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 40, 100, 450));

        jPanel1.setBackground(new java.awt.Color(31, 42, 56));

        btnmenu.setBackground(new java.awt.Color(255, 255, 255));
        btnmenu.setText("<html><div style=\"font-size:30px; cursor:pointer;\">&#9776;</div></html>");
        btnmenu.setBorderPainted(false);
        btnmenu.setContentAreaFilled(false);
        btnmenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnmenu.setFocusPainted(false);
        btnmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 40, Short.MAX_VALUE)
                .addComponent(btnmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 13, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnnewproActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnewproActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnnewproActionPerformed

    private void btnhomemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhomemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnhomemActionPerformed

    private void btntrackingmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntrackingmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btntrackingmActionPerformed

    private void btnmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmenuActionPerformed
        pnlmenu.setVisible(!pnlmenu.isVisible());
    }//GEN-LAST:event_btnmenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmhomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmhomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmhomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmhomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmhomepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnhomem;
    private javax.swing.JButton btnlogout;
    private javax.swing.JButton btnmenu;
    private javax.swing.JButton btnnewpro;
    private javax.swing.JButton btnnewprom;
    private javax.swing.JButton btntrackingm;
    private javax.swing.JButton btnviewprom;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pnlmenu;
    private javax.swing.JButton trackpro;
    private javax.swing.JButton viewpro;
    // End of variables declaration//GEN-END:variables
}
