/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

/**
 *
 * @author Win 10
 */
public class frmnewproducts extends javax.swing.JFrame {

    /**
     * Creates new form frmnewproducts
     */
    public frmnewproducts() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlmenu = new javax.swing.JPanel();
        btnhomem = new javax.swing.JButton();
        btnnewprom = new javax.swing.JButton();
        btnviewprom = new javax.swing.JButton();
        btntrackingm = new javax.swing.JButton();
        btnlogout = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnmenu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblproname = new javax.swing.JTextField();
        txtproname = new javax.swing.JLabel();
        lblqun = new javax.swing.JTextField();
        lblloc = new javax.swing.JTextField();
        txtqun = new javax.swing.JLabel();
        lblnote = new javax.swing.JTextField();
        txtloc = new javax.swing.JLabel();
        txtnote = new javax.swing.JButton();
        btnback1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("WMS ADD");
        setResizable(false);

        pnlmenu.setBackground(new java.awt.Color(31, 42, 56));
        pnlmenu.setBorder(new javax.swing.border.MatteBorder(null));
        pnlmenu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnhomem.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnhomem.setForeground(new java.awt.Color(255, 255, 255));
        btnhomem.setText("home");
        btnhomem.setBorderPainted(false);
        btnhomem.setContentAreaFilled(false);
        btnhomem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnhomem.setFocusPainted(false);
        btnhomem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhomemActionPerformed(evt);
            }
        });

        btnnewprom.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnnewprom.setForeground(new java.awt.Color(255, 255, 255));
        btnnewprom.setText("new products");
        btnnewprom.setBorderPainted(false);
        btnnewprom.setContentAreaFilled(false);
        btnnewprom.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnnewprom.setFocusPainted(false);

        btnviewprom.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnviewprom.setForeground(new java.awt.Color(255, 255, 255));
        btnviewprom.setText("view products");
        btnviewprom.setBorderPainted(false);
        btnviewprom.setContentAreaFilled(false);
        btnviewprom.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnviewprom.setFocusPainted(false);

        btntrackingm.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btntrackingm.setForeground(new java.awt.Color(255, 255, 255));
        btntrackingm.setText("tracking");
        btntrackingm.setBorderPainted(false);
        btntrackingm.setContentAreaFilled(false);
        btntrackingm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btntrackingm.setFocusPainted(false);
        btntrackingm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntrackingmActionPerformed(evt);
            }
        });

        btnlogout.setForeground(new java.awt.Color(255, 255, 255));
        btnlogout.setText("logout\n");
        btnlogout.setBorderPainted(false);
        btnlogout.setContentAreaFilled(false);
        btnlogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnlogout.setFocusPainted(false);

        javax.swing.GroupLayout pnlmenuLayout = new javax.swing.GroupLayout(pnlmenu);
        pnlmenu.setLayout(pnlmenuLayout);
        pnlmenuLayout.setHorizontalGroup(
            pnlmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlmenuLayout.createSequentialGroup()
                .addGroup(pnlmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnnewprom)
                    .addComponent(btnviewprom))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnlmenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnlogout)
                    .addComponent(btntrackingm)
                    .addComponent(btnhomem))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlmenuLayout.setVerticalGroup(
            pnlmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlmenuLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(btnhomem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnnewprom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnviewprom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btntrackingm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 264, Short.MAX_VALUE)
                .addComponent(btnlogout)
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(31, 42, 56));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnmenu.setBackground(new java.awt.Color(255, 255, 255));
        btnmenu.setText("<html><div style=\"font-size:30px; cursor:pointer;\">&#9776;</div></html>");
        btnmenu.setBorderPainted(false);
        btnmenu.setContentAreaFilled(false);
        btnmenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnmenu.setFocusPainted(false);
        btnmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 40, Short.MAX_VALUE)
                .addComponent(btnmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 13, Short.MAX_VALUE))
        );

        jLabel1.setText("product name");

        lblproname.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        txtproname.setText("quantity");

        lblqun.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        lblloc.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        txtqun.setText("storage location");

        lblnote.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        txtloc.setText("notes");

        txtnote.setBackground(new java.awt.Color(31, 42, 56));
        txtnote.setForeground(new java.awt.Color(255, 255, 255));
        txtnote.setText("add");
        txtnote.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnback1.setBackground(new java.awt.Color(31, 42, 56));
        btnback1.setForeground(new java.awt.Color(255, 255, 255));
        btnback1.setText("<html><button onclick=\"history.back()\">   &#8592; Back </button> </html>");
        btnback1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnback1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnback1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtqun)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblloc, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtloc)
                                .addGap(18, 18, 18)
                                .addComponent(lblnote, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtproname)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblproname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblqun, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(txtnote, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnback1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(109, 109, 109)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlmenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnback1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblproname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblqun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtproname))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblloc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtqun))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtloc))
                .addGap(60, 60, 60)
                .addComponent(txtnote, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(pnlmenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btntrackingmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntrackingmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btntrackingmActionPerformed

    private void btnmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmenuActionPerformed
        pnlmenu.setVisible(!pnlmenu.isVisible());
    }//GEN-LAST:event_btnmenuActionPerformed

    private void btnhomemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhomemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnhomemActionPerformed

    private void btnback1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnback1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnback1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windos".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmnewproducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmnewproducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmnewproducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmnewproducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmnewproducts().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback1;
    private javax.swing.JButton btnhomem;
    private javax.swing.JButton btnlogout;
    private javax.swing.JButton btnmenu;
    private javax.swing.JButton btnnewprom;
    private javax.swing.JButton btntrackingm;
    private javax.swing.JButton btnviewprom;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lblloc;
    private javax.swing.JTextField lblnote;
    private javax.swing.JTextField lblproname;
    private javax.swing.JTextField lblqun;
    private javax.swing.JPanel pnlmenu;
    private javax.swing.JLabel txtloc;
    private javax.swing.JButton txtnote;
    private javax.swing.JLabel txtproname;
    private javax.swing.JLabel txtqun;
    // End of variables declaration//GEN-END:variables
}
