/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

/**
 *
 * @author Win 10
 */
public class frmtracking extends javax.swing.JFrame {

    /**
     * Creates new form frmtracking
     */
    public frmtracking() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnback1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnmenu = new javax.swing.JButton();
        pnlmenu = new javax.swing.JPanel();
        btnhomem = new javax.swing.JButton();
        btnnewprom = new javax.swing.JButton();
        btnviewprom = new javax.swing.JButton();
        btntrackingm = new javax.swing.JButton();
        btnlogout = new javax.swing.JButton();
        txtserach = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblproname = new javax.swing.JTextField();
        txtstock = new javax.swing.JTextField();
        txtquanre = new javax.swing.JTextField();
        lblstock = new javax.swing.JLabel();
        lblqunre = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnexcel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("WMS tracking");
        setResizable(false);

        btnback1.setBackground(new java.awt.Color(31, 42, 56));
        btnback1.setForeground(new java.awt.Color(255, 255, 255));
        btnback1.setText("<html><button onclick=\"history.back()\">   &#8592; Back </button> </html>");
        btnback1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnback1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnback1ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(31, 42, 56));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnmenu.setBackground(new java.awt.Color(255, 255, 255));
        btnmenu.setText("<html><div style=\"font-size:30px; cursor:pointer;\">&#9776;</div></html>");
        btnmenu.setBorderPainted(false);
        btnmenu.setContentAreaFilled(false);
        btnmenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnmenu.setFocusPainted(false);
        btnmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 40, Short.MAX_VALUE)
                .addComponent(btnmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(btnmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        pnlmenu.setBackground(new java.awt.Color(31, 42, 56));
        pnlmenu.setBorder(new javax.swing.border.MatteBorder(null));
        pnlmenu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnhomem.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnhomem.setForeground(new java.awt.Color(255, 255, 255));
        btnhomem.setText("home");
        btnhomem.setBorderPainted(false);
        btnhomem.setContentAreaFilled(false);
        btnhomem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnhomem.setFocusPainted(false);
        btnhomem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhomemActionPerformed(evt);
            }
        });

        btnnewprom.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnnewprom.setForeground(new java.awt.Color(255, 255, 255));
        btnnewprom.setText("new products");
        btnnewprom.setBorderPainted(false);
        btnnewprom.setContentAreaFilled(false);
        btnnewprom.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnnewprom.setFocusPainted(false);

        btnviewprom.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnviewprom.setForeground(new java.awt.Color(255, 255, 255));
        btnviewprom.setText("view products");
        btnviewprom.setBorderPainted(false);
        btnviewprom.setContentAreaFilled(false);
        btnviewprom.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnviewprom.setFocusPainted(false);

        btntrackingm.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btntrackingm.setForeground(new java.awt.Color(255, 255, 255));
        btntrackingm.setText("tracking");
        btntrackingm.setBorderPainted(false);
        btntrackingm.setContentAreaFilled(false);
        btntrackingm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btntrackingm.setFocusPainted(false);
        btntrackingm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntrackingmActionPerformed(evt);
            }
        });

        btnlogout.setForeground(new java.awt.Color(255, 255, 255));
        btnlogout.setText("logout\n");
        btnlogout.setBorderPainted(false);
        btnlogout.setContentAreaFilled(false);
        btnlogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnlogout.setFocusPainted(false);

        javax.swing.GroupLayout pnlmenuLayout = new javax.swing.GroupLayout(pnlmenu);
        pnlmenu.setLayout(pnlmenuLayout);
        pnlmenuLayout.setHorizontalGroup(
            pnlmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlmenuLayout.createSequentialGroup()
                .addGroup(pnlmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnnewprom)
                    .addComponent(btnviewprom))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnlmenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnlogout)
                    .addComponent(btntrackingm)
                    .addComponent(btnhomem))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlmenuLayout.setVerticalGroup(
            pnlmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlmenuLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(btnhomem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnnewprom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnviewprom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btntrackingm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 324, Short.MAX_VALUE)
                .addComponent(btnlogout)
                .addContainerGap())
        );

        txtserach.setText("                                     serach by name/id/location");
        txtserach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtserachActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("product name");

        lblproname.setEditable(false);
        lblproname.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        lblstock.setText("in stock");

        lblqunre.setText("reserved quantity");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "source/destination", "balance after op", "quantity affected", "operation tybe", "time and date"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnexcel.setBackground(new java.awt.Color(31, 42, 56));
        btnexcel.setForeground(new java.awt.Color(255, 255, 255));
        btnexcel.setText("export to excel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnback1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(521, 521, 521)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(txtserach, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(133, 133, 133)
                                .addComponent(lblstock)
                                .addGap(186, 186, 186)
                                .addComponent(lblqunre))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtstock, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(150, 150, 150)
                                        .addComponent(txtquanre, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblproname, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnexcel, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(219, 219, 219)))
                .addComponent(pnlmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnback1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(txtserach, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(lblproname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblstock)
                            .addComponent(lblqunre))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtquanre, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtstock, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnexcel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlmenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnback1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnback1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnback1ActionPerformed

    private void btnhomemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhomemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnhomemActionPerformed

    private void btntrackingmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntrackingmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btntrackingmActionPerformed

    private void btnmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmenuActionPerformed
        pnlmenu.setVisible(!pnlmenu.isVisible());
    }//GEN-LAST:event_btnmenuActionPerformed

    private void txtserachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtserachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtserachActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmtracking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmtracking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmtracking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmtracking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmtracking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback1;
    private javax.swing.JButton btnexcel;
    private javax.swing.JButton btnhomem;
    private javax.swing.JButton btnlogout;
    private javax.swing.JButton btnmenu;
    private javax.swing.JButton btnnewprom;
    private javax.swing.JButton btntrackingm;
    private javax.swing.JButton btnviewprom;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField lblproname;
    private javax.swing.JLabel lblqunre;
    private javax.swing.JLabel lblstock;
    private javax.swing.JPanel pnlmenu;
    private javax.swing.JTextField txtquanre;
    private javax.swing.JTextField txtserach;
    private javax.swing.JTextField txtstock;
    // End of variables declaration//GEN-END:variables
}
