/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

/**
 *
 * @author Win 10
 */
public class frmview extends javax.swing.JFrame {

    /**
     * Creates new form frmview
     */
    public frmview() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlmenu = new javax.swing.JPanel();
        btnhomem = new javax.swing.JButton();
        btnnewprom = new javax.swing.JButton();
        btnviewprom = new javax.swing.JButton();
        btntrackingm = new javax.swing.JButton();
        btnlogout = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnmenu = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabpro1 = new javax.swing.JTable();
        btnout1 = new javax.swing.JButton();
        btnin1 = new javax.swing.JButton();
        btnout2 = new javax.swing.JButton();
        btnin2 = new javax.swing.JButton();
        btnout3 = new javax.swing.JButton();
        btnin3 = new javax.swing.JButton();
        btnout4 = new javax.swing.JButton();
        btnin4 = new javax.swing.JButton();
        txtserach = new javax.swing.JTextField();
        btnback1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("WMS VIEW");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlmenu.setBackground(new java.awt.Color(31, 42, 56));
        pnlmenu.setBorder(new javax.swing.border.MatteBorder(null));
        pnlmenu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnhomem.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnhomem.setForeground(new java.awt.Color(255, 255, 255));
        btnhomem.setText("home");
        btnhomem.setBorderPainted(false);
        btnhomem.setContentAreaFilled(false);
        btnhomem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnhomem.setFocusPainted(false);
        btnhomem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhomemActionPerformed(evt);
            }
        });

        btnnewprom.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnnewprom.setForeground(new java.awt.Color(255, 255, 255));
        btnnewprom.setText("new products");
        btnnewprom.setBorderPainted(false);
        btnnewprom.setContentAreaFilled(false);
        btnnewprom.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnnewprom.setFocusPainted(false);

        btnviewprom.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnviewprom.setForeground(new java.awt.Color(255, 255, 255));
        btnviewprom.setText("view products");
        btnviewprom.setBorderPainted(false);
        btnviewprom.setContentAreaFilled(false);
        btnviewprom.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnviewprom.setFocusPainted(false);

        btntrackingm.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btntrackingm.setForeground(new java.awt.Color(255, 255, 255));
        btntrackingm.setText("tracking");
        btntrackingm.setBorderPainted(false);
        btntrackingm.setContentAreaFilled(false);
        btntrackingm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btntrackingm.setFocusPainted(false);
        btntrackingm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntrackingmActionPerformed(evt);
            }
        });

        btnlogout.setForeground(new java.awt.Color(255, 255, 255));
        btnlogout.setText("logout\n");
        btnlogout.setBorderPainted(false);
        btnlogout.setContentAreaFilled(false);
        btnlogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnlogout.setFocusPainted(false);

        javax.swing.GroupLayout pnlmenuLayout = new javax.swing.GroupLayout(pnlmenu);
        pnlmenu.setLayout(pnlmenuLayout);
        pnlmenuLayout.setHorizontalGroup(
            pnlmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlmenuLayout.createSequentialGroup()
                .addGroup(pnlmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnnewprom)
                    .addComponent(btnviewprom))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnlmenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnlogout)
                    .addComponent(btntrackingm)
                    .addComponent(btnhomem))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlmenuLayout.setVerticalGroup(
            pnlmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlmenuLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(btnhomem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnnewprom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnviewprom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btntrackingm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 324, Short.MAX_VALUE)
                .addComponent(btnlogout)
                .addContainerGap())
        );

        getContentPane().add(pnlmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 50, 100, 520));

        jPanel1.setBackground(new java.awt.Color(31, 42, 56));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnmenu.setBackground(new java.awt.Color(255, 255, 255));
        btnmenu.setText("<html><div style=\"font-size:30px; cursor:pointer;\">&#9776;</div></html>");
        btnmenu.setBorderPainted(false);
        btnmenu.setContentAreaFilled(false);
        btnmenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnmenu.setFocusPainted(false);
        btnmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 40, Short.MAX_VALUE)
                .addComponent(btnmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 13, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 0, -1, -1));

        tabpro1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tabpro1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "product name", "quntity", "storag location", "notes"
            }
        ));
        tabpro1.setRowHeight(50);
        jScrollPane2.setViewportView(tabpro1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 590, 350));

        btnout1.setBackground(new java.awt.Color(204, 204, 204));
        btnout1.setText("output");
        getContentPane().add(btnout1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 270, 70, 20));

        btnin1.setBackground(new java.awt.Color(204, 204, 204));
        btnin1.setText("input");
        getContentPane().add(btnin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 250, 70, 20));

        btnout2.setBackground(new java.awt.Color(204, 204, 204));
        btnout2.setText("output");
        getContentPane().add(btnout2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 320, 70, 20));

        btnin2.setBackground(new java.awt.Color(204, 204, 204));
        btnin2.setText("input");
        btnin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnin2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 300, 70, 20));

        btnout3.setBackground(new java.awt.Color(204, 204, 204));
        btnout3.setText("output");
        getContentPane().add(btnout3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 370, 70, 20));

        btnin3.setBackground(new java.awt.Color(204, 204, 204));
        btnin3.setText("input");
        getContentPane().add(btnin3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 350, 70, 20));

        btnout4.setBackground(new java.awt.Color(204, 204, 204));
        btnout4.setText("output");
        getContentPane().add(btnout4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 420, 70, 20));

        btnin4.setBackground(new java.awt.Color(204, 204, 204));
        btnin4.setText("input");
        getContentPane().add(btnin4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 400, 70, 20));

        txtserach.setText("                                     serach by name/id/location");
        txtserach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtserachActionPerformed(evt);
            }
        });
        getContentPane().add(txtserach, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 450, 30));

        btnback1.setBackground(new java.awt.Color(31, 42, 56));
        btnback1.setForeground(new java.awt.Color(255, 255, 255));
        btnback1.setText("<html><button onclick=\"history.back()\">   &#8592; Back </button> </html>");
        btnback1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnback1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnback1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnback1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnhomemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhomemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnhomemActionPerformed

    private void btntrackingmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntrackingmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btntrackingmActionPerformed

    private void btnmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmenuActionPerformed
        pnlmenu.setVisible(!pnlmenu.isVisible());
    }//GEN-LAST:event_btnmenuActionPerformed

    private void txtserachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtserachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtserachActionPerformed

    private void btnin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnin2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnin2ActionPerformed

    private void btnback1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnback1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnback1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmview().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback1;
    private javax.swing.JButton btnhomem;
    private javax.swing.JButton btnin1;
    private javax.swing.JButton btnin2;
    private javax.swing.JButton btnin3;
    private javax.swing.JButton btnin4;
    private javax.swing.JButton btnlogout;
    private javax.swing.JButton btnmenu;
    private javax.swing.JButton btnnewprom;
    private javax.swing.JButton btnout1;
    private javax.swing.JButton btnout2;
    private javax.swing.JButton btnout3;
    private javax.swing.JButton btnout4;
    private javax.swing.JButton btntrackingm;
    private javax.swing.JButton btnviewprom;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pnlmenu;
    private javax.swing.JTable tabpro1;
    private javax.swing.JTextField txtserach;
    // End of variables declaration//GEN-END:variables
}
